application: dailydoog
version: new-responsive-3-nd
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /resources
  static_dir: resources
  http_headers:
    Access-Control-Allow-Origin: "*"
    
- url: /robots.txt
  static_files: resources/crawler/robots.txt
  upload: resources/crawler/robots.txt

- url: .*
  script: main.py

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on