application: doogport
version: test-1a
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /resources
  static_dir: resources

- url: .*
  script: main.py

libraries:
- name: django
  version: latest

builtins:
- remote_api: on