application: dailydoog
version: new-responsive-1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /resources
  static_dir: resources
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: .*
  script: main.py

libraries:
- name: django
  version: latest

builtins:
- remote_api: on